apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-k8s
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      containers:
      - name: flask-k8s
        image: ghcr.io/monis121hassan/flask-k8s:13
        ports:
          - containerPort: 5000
      imagePullSecrets:
        - name: ghcr-secret