name: CI/CD - Build & Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u monis121hassan --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/monis121hassan/flask-k8s:${{ github.run_number }} .

      - name: Push Docker image
        run: docker push ghcr.io/monis121hassan/flask-k8s:${{ github.run_number }}

      - name: Update K8s manifest image tag
        run: |
          sed -i "s#ghcr.io/.*/flask-k8s:.*#ghcr.io/monis121hassan/flask-k8s:${{ github.run_number }}#g" k8s/deployment.yaml
          git config --global user.name "monis121hassan"
          git config --global user.email "monis121hassan@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Updated image tag to ${{ github.run_number }}"
          git push